name: Openslide_ENV
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py310ha9d4c09_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - double-conversion=3.3.1=h5888daf_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=8.0.0=gpl_hbbdf940_906
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.44.3=h2b0a6b4_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - glslang=16.0.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=12.1.0=h15599e2_0
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - icu=75.1=he02047a_0
  - imath=3.2.1=hde8ca8f_0
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - jasper=4.2.8=he3c4edf_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - level-zero=1.24.3=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=12_h832b8c9_netlib
  - libclang-cpp21.1=21.1.2=default_h99862b1_3
  - libclang13=21.1.2=default_h746c552_3
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdicom=1.2.0=hb03c661_1
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.1=hb25bd0a_0
  - libjxl=0.11.1=h6cb5226_4
  - liblapack=3.9.0=12_hd37a5e2_netlib
  - liblapacke=3.9.0=12_hce4cc19_netlib
  - libllvm21=21.1.3=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=h46f56fc_0
  - libopencv=4.12.0=qt6_py310h62951e6_605
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libprotobuf=6.31.1=h9ef548d_1
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=257.9=h996ca69_0
  - libtiff=4.7.1=h8261f1e_0
  - libudev1=257.9=h085a93f_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.2=he9a06e4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.12.0=hca5e8e5_0
  - libxml2=2.15.0=h26afc86_1
  - libxml2-16=2.15.0=ha9997c6_1
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.10.0=h5888daf_1
  - mpg123=1.32.9=hc50e24c_0
  - ncurses=6.5=h7934f7d_0
  - numexpr=2.11.0=py310hccd6f0b_1
  - numpy=2.2.5=py310hc213724_1
  - numpy-base=2.2.5=py310hf387b04_1
  - ocl-icd=2.3.3=hb9d3cd8_0
  - openblas=0.3.4=ha44fe06_0
  - opencl-headers=2025.06.13=h5888daf_0
  - opencv=4.12.0=qt6_py310hec850f8_605
  - openexr=3.4.1=hfdf38da_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.3=h55fea9a_1
  - openjph=0.24.1=h8d634f6_0
  - openldap=2.6.10=he970967_0
  - openslide=4.0.0=h582fa3c_6
  - openslide-python=1.4.2=py310h3616527_2
  - openssl=3.5.4=h26f9b46_0
  - pandas=2.3.3=py310h505adc9_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pillow=11.3.0=py310h6557065_3
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a8bead_2
  - py-opencv=4.12.0=qt6_py310h89973df_605
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-lmdb=1.7.5=py310h25320af_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=py310h06a4308_0
  - qt6-main=6.9.3=h5c1c036_0
  - rav1e=0.7.1=h8fae777_3
  - readline=8.3=hc2a1206_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.24=h68140b3_0
  - shaderc=2025.4=h3e344bc_0
  - six=1.17.0=py310h06a4308_0
  - snappy=1.2.2=h03e3b7b_0
  - spirv-tools=2025.4=hb700be7_0
  - sqlite=3.50.2=hb25bd0a_1
  - svt-av1=3.1.2=hecca717_0
  - tbb=2022.2.0=hb60516a_1
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=py310h2f386ee_0
  - tzdata=2025b=h04d1e81_0
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - anyio==4.11.0
      - braceexpand==0.1.7
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - filelock==3.19.1
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - mamba-ssm==2.2.6.post3
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - ninja==1.13.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.6.2
      - setuptools==80.9.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sympy==1.14.0
      - timm==1.0.21
      - tokenizers==0.22.1
      - torch==2.9.0
      - torchvision==0.24.0
      - transformers==4.57.1
      - triton==3.5.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - webdataset==1.0.2
prefix: /root/miniconda3/envs/Openslide_ENV
